main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  # accounts
  path('accounts/signup/', views.signup, name='signup'),
  path('update_profile/', views.update_profile, name='update_profile'),
  # basic views
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  # game views/actions
  path('games/search/', views.games_search, name='games_search'),
  path('games/lookup/', views.game_lookup, name='game_lookup'),
  path('games/bgg_find/', views.bgg_find, name='bgg_find'),
  path('games/add_offer/', views.add_offer, name='add_offer'),
  # offer views/actions
  path('offers/<int:offer_id>/', views.offer_details, name='offer_details'),
  path('offers/<int:pk>/update/', views.OfferUpdate.as_view(), name='offer_update'),
  path('offers/<int:pk>/delete/', views.OfferDelete.as_view(), name='offer_delete'),
  path('offer/search/', views.offer_search, name="offer_search"),
  # user views
  path('users/profile/', views.profile, name='profile'),
  path('users/<int:user_id>/', views.user_page, name='user_page'),
  # messages views/actions
  path('messages/create/', views.message_create, name='message_create'),
  path('messages/send/', views.message_send, name='message_send'),
  path('messages/view/', views.messages_view, name='messages_view'),
  path('messages/<int:pk>/update/', views.MessageUpdate.as_view(), name='message_update'),
  path('messages/<int:pk>/delete/', views.MessageDelete.as_view(), name='message_delete'),
  # reply views/actions
  # path('reply/new', views.reply_new, name='reply_new'),
  path('reply/create', views.reply_create, name='reply_create'),
  path('reply/<int:pk>/update/', views.ReplyUpdate.as_view(), name='reply_update'),
  # path('reply/<int:pk>/delete/', views.ReplyDelete.as_view(), name='reply_delete'),
  path('reply/<int:reply_id>/delete/', views.reply_delete, name='reply_delete'),
]

table_top_swap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

CONDITIONS =(
  ('1', 'New'),
  ('2', 'Like New'),
  ('3', 'Good'),
  ('4', 'Fair'),
  ('5', 'Poor'),
)

LISTS =(
  ('O', 'Offer List'),
  ('W', 'Wish List')
)

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  icon = models.URLField(max_length=300, blank=True)

  @receiver(post_save, sender=User)
  def create_user_profile(sender, instance, created, **kwargs):
      if created:
          Profile.objects.create(user=instance)

  @receiver(post_save, sender=User)
  def save_user_profile(sender, instance, **kwargs):
      instance.profile.save()


class Offer(models.Model):
  title = models.CharField(max_length=200)
  bgg_slug = models.IntegerField()
  year_published = models.IntegerField()
  image = models.CharField(max_length=200)
  thumbnail = models.CharField(max_length=200)
  condition = models.CharField(
    max_length=1,
    choices = CONDITIONS,
    default = CONDITIONS[2][0]
  )
  comment = models.TextField(max_length=500)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  list_type = models.CharField(
    ('Which list?'),
    max_length=1,
    choices = LISTS
  )

  def __str__(self):
      return self.title

  def get_absolute_url(self):
    return reverse('offer_details', kwargs={'offer_id': self.id})
  
class Message(models.Model):
  message = models.TextField(max_length=300)
  sender = models.ForeignKey(User, on_delete=models.CASCADE)
  receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')

  def get_absolute_url(self):
    return reverse('messages_view')#, kwargs={'message_id': self.id})

class Reply(models.Model):
  reply = models.TextField(max_length=300)
  sender = models.ForeignKey(User, on_delete=models.CASCADE)
  message = models.ForeignKey(Message, on_delete=models.CASCADE)

  def get_absolute_url(self):
    return reverse('messages_view')#, kwargs={'message_id': self.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Offer, Profile, Message, Reply
from django import forms
from django.contrib.auth.models import User

class OfferForm(ModelForm):
  class Meta:
    model = Offer
    # fields = ['title', 'bgg_slug', 'year_published', 'image', 'thumbnail', 'condition', 'comment']
    # exclude = ['title', 'bgg_slug', 'year_published', 'image', 'thumbnail', 'user']
    fields = '__all__'
    widgets = {
      'user': forms.HiddenInput(),
      'title': forms.HiddenInput(),
      'bgg_slug': forms.HiddenInput(),
      'image': forms.HiddenInput(),
      'thumbnail': forms.HiddenInput(),
      'year_published': forms.HiddenInput(),
    }

class UserForm(ModelForm):
  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'email')

class ProfileForm(ModelForm):
  class Meta:
    model = Profile
    fields = ('icon',)

class MessageForm(ModelForm):
  class Meta:
    model = Message
    fields = '__all__'
    widgets = {
      'sender': forms.HiddenInput(),
      'receiver': forms.HiddenInput(),
    }

class ReplyForm(ModelForm):
  class Meta:
    model = Reply
    fields = '__all__'
    widgets = {
      'sender': forms.HiddenInput(),
      'message': forms.HiddenInput(),
    }

main_app/views.py
from django.views.generic.edit import UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from .games_search import search, find
from .forms import OfferForm, UserForm, ProfileForm, MessageForm, ReplyForm
from .models import Offer, Message, Reply

# to protect view classes: put LoginRequiredMixin, into the class inheritance

# accounts

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

@login_required
def update_profile(request):
  if request.method == 'POST':
    user_form = UserForm(request.POST, instance=request.user)
    profile_form = ProfileForm(request.POST, instance=request.user.profile)
    if user_form.is_valid() and profile_form.is_valid():
      user_form.save()
      profile_form.save()
      #messages.success(request, _('Your profile was successfully updated!'))
      return redirect('/users/profile/')
    #else:
      #messages.error(request, _('Please correct the error below.'))
  else:
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)
  return render(request, 'edit_profile.html', {
    'user_form': user_form,
    'profile_form': profile_form
  })

# home page

def home(request):
  recent = Offer.objects.order_by('-id')[:10]
  return render(request, 'home.html', {'recent': recent})

# about page

def about(request):
  return render(request, 'about.html')

# games views/actions

def games_search(request):
  return render(request, 'games_search.html')

def game_lookup(request):
  results = search(request.POST['query'])
  return render(request, 'games_search.html', { 'results': results })

@login_required
def bgg_find(request):
  result = find(request.POST['objectid'])
  result['title'] = request.POST['title']
  offer_form = OfferForm(initial={ 
    'title': result['title'],
    'bgg_slug': result['bgg_slug'],
    'year_published': result['year_published'],
    'thumbnail': result['thumbnail'],
    'image': result['image'],
    'user': request.user
   })
  return render(request, 'amend_game.html', {'result': result, 'offer_form': offer_form })

@login_required
def add_offer(request):
  form = OfferForm(request.POST)
  if form.is_valid():
    new_offer = form.save(commit=False)
    # new_offer.list_type = 'offer'
    new_offer.save()
  return redirect('/users/profile/')

# offer views/actions

@login_required
def offer_details(request, offer_id):
  offer = Offer.objects.get(id=offer_id)
  return render(request, 'offers/details.html', { 'offer': offer })

class OfferUpdate(LoginRequiredMixin, UpdateView):
  model = Offer
  fields = ['condition', 'comment']

class OfferDelete(LoginRequiredMixin, DeleteView):
  model = Offer
  success_url = '/users/profile/'

@login_required
def offer_search(request):
  offers = Offer.objects.filter(title__icontains=request.POST['query']).exclude(user=request.user)
  return render(request, 'home.html', {'offers':offers})


# user views/actions

@login_required
def profile(request):
  offers = Offer.objects.filter(user=request.user, list_type='O')
  wishes = Offer.objects.filter(user=request.user, list_type='W')
  user = request.user
  return render(request, 'profile.html', { 'offers': offers, 'wishes': wishes, 'user': user})

def user_page(request, user_id):
  user_focus = User.objects.get(id=user_id)
  user_offers = Offer.objects.filter(user=user_id, list_type='O')
  user_wishes = Offer.objects.filter(user=user_id, list_type='W')
  return render(request, 'users/details.html', {
    'user_focus': user_focus,
    'user_offers': user_offers,
    'user_wishes': user_wishes
  })

# messages views and actions

@login_required
def message_create(request):
  message_form = MessageForm(initial={ 
    'sender': request.user.id,
    'receiver': request.POST['receiver']
  })
  return render(request, 'messages/create_message.html', { 'message_form': message_form })

@login_required
def message_send(request):
  form = MessageForm(request.POST)
  if form.is_valid():
    new_message = form.save(commit=False)
    new_message.save()
  return redirect('/messages/view/')

@login_required
def messages_view(request):
  sent_messages = Message.objects.filter(sender=request.user)
  received_messages = Message.objects.filter(receiver=request.user)
  return render(request, 'messages/view_messages.html', { 
    'sent_messages': sent_messages,
    'received_messages': received_messages
  })

class MessageUpdate(LoginRequiredMixin, UpdateView):
  model = Message
  fields = ['message']

class MessageDelete(LoginRequiredMixin, DeleteView):
  model = Message
  success_url = '/messages/view/'

# reply views/actions

# def reply_new(request):
#   message = Message.objects.get(id=request.POST['message'])
#   reply_form = ReplyForm(initial={ 
#     'sender': request.user.id,
#     'message': request.POST['message']
#   })
#   return render(request, 'replies/reply_new.html', { 
#     'reply_form': reply_form ,
#     'message': message
#   })

@login_required
def reply_create(request):
  form = ReplyForm(request.POST)
  if form.is_valid():
    new_message = form.save(commit=False)
    new_message.save()
  return redirect('/messages/view/')

class ReplyUpdate(LoginRequiredMixin, UpdateView):
  model = Reply
  fields = ['reply']

# class ReplyDelete(LoginRequiredMixin, DeleteView):
#   model = Reply
#   success_url = '/messages/view/'

@login_required
def reply_delete(request, reply_id):
  Reply.objects.get(id=reply_id).delete()
  return redirect('/messages/view/')

main_app/templates/messages/create_message.html
{% extends 'base.html' %}

{% block title %}Send a message{% endblock %}

{% block content %}

<h1>Send Message</h1>

<div class="general-card">
  <form action="{% url 'message_send' %}" method="POST">
    {% csrf_token %}
    {{ message_form.as_p }}
    <input type='submit' value='Send Message' class="button">
  </form>
</div>

{% endblock %}

main_app/templates/messages/view_messages.html
{% extends 'base.html' %}

{% block title %}View Messages{% endblock %}

{% block content %}

<h1>View Message</h1>

<div class="messages-container">
  <div class="message-column">
    <h3>Sent Mesages</h3>
    {% if sent_messages %}
      {% for message in sent_messages %}
        <div class="message-card">
          <div>
            <div class="message-header">
              {% if message.sender.profile.icon %}
                <img src="{{ message.sender.profile.icon }}" class="message-icon"><br>
              {% else %}
                <img src="https://i.imgur.com/zTpOPgB.png" class="message-icon"><br>
              {% endif %}
              <p>&nbsp;&nbsp;{{ message.sender }}</p>
            </div>
            <div class="message-body">
              <p>{{ message.message }}</p>
            </div>
            <div class="message-actions">
              <a href="{% url 'message_update' message.id %}" class="button">Edit</a>
              <a href="{% url 'message_delete' message.id %}" class="button">Delete</a>
            </div>
          </div>
          {% for reply in message.reply_set.all %}
            <div class="reply-bump">
              <div class="message-header">
                {% if reply.sender.profile.icon %}
                  <img src="{{ reply.sender.profile.icon }}" class="message-icon"><br>
                {% else %}
                  <img src="https://i.imgur.com/zTpOPgB.png" class="message-icon"><br>
                {% endif %}
                <p>&nbsp;&nbsp;{{ reply.sender }}</p>
              </div>
              <div class="message-body reply-width">
                <p>{{ reply.reply }}</p>
              </div>
              {% if reply.sender.id == user.id %}
              <div class="message-actions">
                <a href="{% url 'reply_update' reply.id %}" class="button">Edit</a>
                <a href="{% url 'reply_delete' reply.id %}" class="button">Delete</a>
              </div>
              {% endif %}
            </div>
          {% endfor %}
          <br>
          <form action="{% url 'reply_create' %}" method="POST">
            {% csrf_token %}
            <input type='text' name="reply">
            <input type="hidden" name="sender" value="{{ user.id }}">
            <input type="hidden" name="message" value="{{ message.id }}">
            <input type='submit' value='Add Reply' class="button">
          </form>
        </div>
      {% endfor %}
    {% else %}
      <p>You have no sent messages at the moment.</p>
    {% endif %}
  </div>
  <div class="message-column">
    <h3>Received Mesages</h3>
    {% if received_messages %}
      {% for message in received_messages %}
        <div class="message-card">
          <div>
            <div class="message-header">
              {% if message.sender.profile.icon %}
                <img src="{{ message.sender.profile.icon }}" class="message-icon"><br>
              {% else %}
                <img src="https://i.imgur.com/zTpOPgB.png" class="message-icon"><br>
              {% endif %}
              <p>&nbsp;&nbsp;{{ message.sender }}</p>
            </div>
            <div class="message-body">
              <p>{{ message.message }}</p>
            </div>
          </div>
          {% for reply in message.reply_set.all %}
            <div class="reply-bump">
              <div class="message-header">
                {% if reply.sender.profile.icon %}
                  <img src="{{ reply.sender.profile.icon }}" class="message-icon"><br>
                {% else %}
                  <img src="https://i.imgur.com/zTpOPgB.png" class="message-icon"><br>
                {% endif %}
                <p>&nbsp;&nbsp;{{ reply.sender }}</p>
              </div>
              <div class="message-body reply-width">
                <p>{{ reply.reply }}</p>
              </div>
              {% if reply.sender.id == user.id %}
              <div class="message-actions">
                <a href="{% url 'reply_update' reply.id %}" class="button">Edit</a>
                <a href="{% url 'reply_delete' reply.id %}" class="button">Delete</a>
              </div>
              {% endif %}
            </div>
          {% endfor %}
          <br>
          <form action="{% url 'reply_create' %}" method="POST">
            {% csrf_token %}
            <input type='text' name="reply">
            <input type="hidden" name="sender" value="{{ user.id }}">
            <input type="hidden" name="message" value="{{ message.id }}">
            <input type='submit' value='Add Reply' class="button">
          </form>
        </div>
      {% endfor %}
    {% else %}
      <p>You have no received messages at the moment.</p>
    {% endif %}
  </div>
</div>
{% endblock %}